/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StockBot;

import java.util.*;
import Stock.Stock;
import StockScrapper.StockScrapper;

// UI
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

// Stock Data
import org.patriques.output.timeseries.data.StockData;


public class App implements ActionListener{

    final static int REFRESH_RATE = 10;

    private static JLabel price = new JLabel("MSFT Open:  0     ");
    private static JLabel current_balance = new JLabel("Balance:  0     ");
    private static JLabel amountStock = new JLabel("Amount of Stock:  0     ");
    private static JFrame frame = new JFrame();

    private static int num_stock = 0;
    private static double balance = 0;

    public App() {
        // the clickable button
        JButton button = new JButton("Buy Stock");
        button.addActionListener(this);

        // the panel with the button and text
        JPanel panel = new JPanel();
        panel.setBorder(BorderFactory.createEmptyBorder(30, 30, 10, 30));
        panel.setLayout(new GridLayout(0, 1));
        panel.add(button);
        panel.add(price);
        panel.add(current_balance);
        panel.add(amountStock);

        // set up the frame and display it
        frame.add(panel, BorderLayout.CENTER);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setTitle("StockBot");
        frame.pack();
        frame.setSize(500, 500);
        frame.setVisible(true);
    }

    // process the button clicks
    public void actionPerformed(ActionEvent e) {
        num_stock++;
        amountStock.setText("Amount of Stock:  " + num_stock);
        
        Stock msft = new Stock("MSFT");
        StockData msft_stockdata = msft.getData();
        balance -= msft_stockdata.getOpen();
        current_balance.setText("Balance:  " + balance);

    }

    public static void main(String[] args) {
        StockScrapper msft = new StockScrapper("MSFT");
        msft.getData();
        // new App();

        // try {  
        //     while (true) {
        //         Stock msft = new Stock("MSFT");
        //         StockData msft_stockdata = msft.getData();
        //         price.setText("MSFT Open: " + Double.toString(msft_stockdata.getOpen()));
        //         System.out.println(new Date());
        //         Thread.sleep(REFRESH_RATE * 1000); // change to 1000
        //         System.out.println("Breaking");
        //     }    
        // } catch (InterruptedException e) {
        //     e.printStackTrace();
        // }
        // System.out.println("Finished.");
    }
}
