/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StockBot;
import java.util.*;
import Test.Test;
import Stock.Stock;

// UI
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;


public class App {

    final static int REFRESH_RATE = 60;

    public static void main(String[] args) {

        Test a = new Test(10);
        System.out.println("Foo: " + a.getFoo());
        System.out.println("Success");
        try {  
            while (true) {
                Stock msft = new Stock("MSFT");
                msft.getData();
                System.out.println(new Date());
                Thread.sleep(REFRESH_RATE * 1); // change to 1000
                break; // uncomment for continous
            }    
        } catch (InterruptedException e) {
        e.printStackTrace();
        }
    }  
}
